version: "3"
services:
  api:
    build: .
    container_name: hitchhiker-api
    networks:
      - hitchnet
    ports:
      - "5005:5000"

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs/:/etc/caddy/certs
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
    networks:
      - hitchnet

networks:
  hitchnet:
    external: true

volumes:
  caddy_data:
  caddy_config:
