version: "3.8"

services:
  openwrt:
    build: .
    image: openwrt-qemu
    ports:
      - "8080:80" # Port forwarding for web interface
      - "2222:22" # Port forwarding for SSH
    volumes:
      - openwrt_data:/opt/openwrt-data
    healthcheck:
      test: ["CMD", "your_health_check_command"]
      interval: 60s
      timeout: 15s
      retries: 3

volumes:
  openwrt_data:

networks:
  hitchnet:
    external: true
